import type { SkillDef } from '@/types'

export const SKILLS: SkillDef[] = [
  // ── BEGINNER ────────────────────────────────────────────────────────────────
  {
    id: 'dead_hang',
    name: 'Dead Hang',
    description: 'Atârnă la bara fixă timp de 30 de secunde.',
    level: 'BEGINNER',
    icon: '🤸',
    coinsReward: 10,
    requirements: [],
  },
  {
    id: 'knee_pushup',
    name: 'Flotări pe genunchi',
    description: 'Execută 10 flotări pe genunchi cu formă corectă.',
    level: 'BEGINNER',
    icon: '💪',
    coinsReward: 10,
    requirements: [],
  },
  {
    id: 'basic_squat',
    name: 'Squat de bază',
    description: 'Execută 20 de squaturi complete.',
    level: 'BEGINNER',
    icon: '🦵',
    coinsReward: 10,
    requirements: [],
  },
  {
    id: 'hollow_body',
    name: 'Hollow Body Hold',
    description: 'Menține poziția hollow body timp de 20 de secunde.',
    level: 'BEGINNER',
    icon: '🏋️',
    coinsReward: 10,
    requirements: [],
  },
  {
    id: 'arch_body',
    name: 'Arch Body Hold',
    description: 'Menține poziția arch body timp de 20 de secunde.',
    level: 'BEGINNER',
    icon: '🌉',
    coinsReward: 10,
    requirements: [],
  },

  // ── INTERMEDIATE ─────────────────────────────────────────────────────────────
  {
    id: 'pushup',
    name: 'Flotări',
    description: 'Execută 20 de flotări complete cu formă perfectă.',
    level: 'INTERMEDIATE',
    icon: '💪',
    coinsReward: 20,
    requirements: ['knee_pushup'],
  },
  {
    id: 'pullup',
    name: 'Tracțiuni',
    description: 'Execută 5 tracțiuni complete.',
    level: 'INTERMEDIATE',
    icon: '🏋️',
    coinsReward: 25,
    requirements: ['dead_hang'],
  },
  {
    id: 'dip',
    name: 'Dips',
    description: 'Execută 10 dips pe bare paralele.',
    level: 'INTERMEDIATE',
    icon: '⬇️',
    coinsReward: 20,
    requirements: ['pushup'],
  },
  {
    id: 'pike_pushup',
    name: 'Pike Push-up',
    description: 'Execută 10 pike push-up-uri.',
    level: 'INTERMEDIATE',
    icon: '🔻',
    coinsReward: 20,
    requirements: ['pushup'],
  },
  {
    id: 'lsit',
    name: 'L-Sit',
    description: 'Menține poziția L-sit timp de 10 secunde.',
    level: 'INTERMEDIATE',
    icon: '🪑',
    coinsReward: 25,
    requirements: ['hollow_body', 'dip'],
  },
  {
    id: 'pistol_squat',
    name: 'Pistol Squat',
    description: 'Execută 5 pistol squaturi pe fiecare picior.',
    level: 'INTERMEDIATE',
    icon: '🦵',
    coinsReward: 25,
    requirements: ['basic_squat'],
  },
  {
    id: 'australian_pullup',
    name: 'Australian Pull-up',
    description: 'Execută 15 australian pull-up-uri.',
    level: 'INTERMEDIATE',
    icon: '🦘',
    coinsReward: 15,
    requirements: ['dead_hang'],
  },
  {
    id: 'dragon_flag_neg',
    name: 'Dragon Flag Negativ',
    description: 'Execută 5 repetări negative de dragon flag.',
    level: 'INTERMEDIATE',
    icon: '🐉',
    coinsReward: 25,
    requirements: ['hollow_body'],
  },

  // ── ADVANCED ──────────────────────────────────────────────────────────────────
  {
    id: 'muscle_up',
    name: 'Muscle-Up',
    description: 'Execută un muscle-up complet la bară.',
    level: 'ADVANCED',
    icon: '⚡',
    coinsReward: 50,
    requirements: ['pullup', 'dip'],
  },
  {
    id: 'handstand',
    name: 'Stând pe mâini',
    description: 'Menține handstand-ul timp de 10 secunde.',
    level: 'ADVANCED',
    icon: '🤸',
    coinsReward: 50,
    requirements: ['pike_pushup'],
  },
  {
    id: 'hspu',
    name: 'Handstand Push-up',
    description: 'Execută un handstand push-up complet.',
    level: 'ADVANCED',
    icon: '🔝',
    coinsReward: 60,
    requirements: ['handstand', 'pike_pushup'],
  },
  {
    id: 'diamond_pushup',
    name: 'Diamond Push-up',
    description: 'Execută 15 diamond push-up-uri.',
    level: 'ADVANCED',
    icon: '💎',
    coinsReward: 30,
    requirements: ['pushup'],
  },
  {
    id: 'chest_to_bar',
    name: 'Chest-to-Bar Pull-up',
    description: 'Execută 3 chest-to-bar pull-up-uri.',
    level: 'ADVANCED',
    icon: '🎯',
    coinsReward: 35,
    requirements: ['pullup'],
  },
  {
    id: 'dragon_flag',
    name: 'Dragon Flag',
    description: 'Execută 3 dragon flag-uri complete.',
    level: 'ADVANCED',
    icon: '🐲',
    coinsReward: 50,
    requirements: ['dragon_flag_neg'],
  },
  {
    id: 'tuck_front_lever',
    name: 'Tuck Front Lever',
    description: 'Menține tuck front lever timp de 5 secunde.',
    level: 'ADVANCED',
    icon: '⚓',
    coinsReward: 50,
    requirements: ['chest_to_bar'],
  },
  {
    id: 'tuck_planche',
    name: 'Tuck Planche',
    description: 'Menține tuck planche timp de 5 secunde.',
    level: 'ADVANCED',
    icon: '✈️',
    coinsReward: 50,
    requirements: ['lsit', 'diamond_pushup'],
  },

  // ── ELITE ────────────────────────────────────────────────────────────────────
  {
    id: 'front_lever',
    name: 'Front Lever',
    description: 'Menține front lever timp de 5 secunde.',
    level: 'ELITE',
    icon: '🏆',
    coinsReward: 100,
    requirements: ['tuck_front_lever'],
  },
  {
    id: 'back_lever',
    name: 'Back Lever',
    description: 'Menține back lever timp de 5 secunde.',
    level: 'ELITE',
    icon: '🥇',
    coinsReward: 100,
    requirements: ['tuck_front_lever'],
  },
  {
    id: 'planche',
    name: 'Planche',
    description: 'Menține planche timp de 3 secunde.',
    level: 'ELITE',
    icon: '🦅',
    coinsReward: 150,
    requirements: ['tuck_planche'],
  },
  {
    id: 'one_arm_pullup',
    name: 'One-Arm Pull-up',
    description: 'Execută un one-arm pull-up complet.',
    level: 'ELITE',
    icon: '☝️',
    coinsReward: 150,
    requirements: ['chest_to_bar', 'muscle_up'],
  },
  {
    id: 'one_arm_pushup',
    name: 'One-Arm Push-up',
    description: 'Execută 3 one-arm push-up-uri pe fiecare braț.',
    level: 'ELITE',
    icon: '👆',
    coinsReward: 100,
    requirements: ['diamond_pushup'],
  },
  {
    id: 'ring_muscle_up',
    name: 'Ring Muscle-Up',
    description: 'Execută un muscle-up la inele.',
    level: 'ELITE',
    icon: '🔗',
    coinsReward: 120,
    requirements: ['muscle_up'],
  },
]

export const SKILL_LEVEL_ORDER: Record<string, number> = {
  BEGINNER: 0,
  INTERMEDIATE: 1,
  ADVANCED: 2,
  ELITE: 3,
}

export const SKILL_LEVEL_LABELS: Record<string, string> = {
  BEGINNER: 'Începător',
  INTERMEDIATE: 'Intermediar',
  ADVANCED: 'Avansat',
  ELITE: 'Elite',
}

export const SKILL_LEVEL_COLORS: Record<string, string> = {
  BEGINNER: '#6B7280',
  INTERMEDIATE: '#3B82F6',
  ADVANCED: '#8B5CF6',
  ELITE: '#F59E0B',
}

export function getSkillById(id: string): SkillDef | undefined {
  return SKILLS.find(s => s.id === id)
}
